openapi: 3.0.0
info:
  version: 0.1.0
  title: Warehouse Service
paths:
  /data/ad/impressions:
    post:
      summary: Record a batch of ad impressions
      operationId: data-ad-impressions
      requestBody:
        description: A batch of ad impressions
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataAdImpressions"
      x-amazon-apigateway-integration:
        type: AWS
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:firehose:action/PutRecordBatch
        # credentials: null
        requestTemplates:
          application/json: !Sub |
            #set($newline = "
            ")
            {
              "DeliveryStreamName": "${stageVariables.AdImpressionsDeliveryStream}",
              "Records": [
                #foreach($elem in $input.path('$.impressions'))
                #set($val = $input.json("$.impressions[$foreach.index]"))
                #set($rec = "${!val}${!newline}")
                { "Data": "$util.base64Encode($rec)" }#if($foreach.hasNext),#end
                #end
              ]
            }
        requestParameters:
          integration.request.header.Content-Type: "'x-amz-json-1.1'"
        responses:
          '200':
            statusCode: 200
            responseTemplates:
              application/json: |
                {
                  "failed_count": $input.path("$.FailedPutCount"),
                  "records": [
                    #foreach($record in $input.path("$.RequestResponses"))
                    {
                      #if($record.keySet().contains("ErrorCode"))
                      "failed": true,
                      "error_code": "$record.ErrorCode",
                      "error_message": "$record.ErrorMessage"
                      #else
                      "failed": false
                      #end
                    }#if($foreach.hasNext),#end
                    #end
                  ]
                }
      responses:
        '200':
          description: |
            The batch was processed.  Some impressions may not have
            been processed.  The response contains a list of
            impressions in the same order submitted, indicating which
            succeeded and which failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchWriteResponse"
  /data/ad/clicks:
    post:
      summary: Record a batch of ad clicks
      operationId: data-ad-clicks
      requestBody:
        description: A batch of ad clicks
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataAdClicks"
      x-amazon-apigateway-integration:
        type: AWS
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:firehose:action/PutRecordBatch
        # credentials: null
        requestTemplates:
          application/json: !Sub |
            #set($newline = "
            ")
            {
              "DeliveryStreamName": "${stageVariables.AdClicksDeliveryStream}",
              "Records": [
                #foreach($elem in $input.path('$.clicks'))
                #set($val = $input.json("$.clicks[$foreach.index]"))
                #set($rec = "${!val}${!newline}")
                { "Data": "$util.base64Encode($rec)" }#if($foreach.hasNext),#end
                #end
              ]
            }
        requestParameters:
          integration.request.header.Content-Type: "'x-amz-json-1.1'"
        responses:
          '200':
            statusCode: 200
            responseTemplates:
              application/json: |
                {
                  "failed_count": $input.path("$.FailedPutCount"),
                  "records": [
                    #foreach($record in $input.path("$.RequestResponses"))
                    {
                      #if($record.keySet().contains("ErrorCode"))
                      "failed": true,
                      "error_code": "$record.ErrorCode",
                      "error_message": "$record.ErrorMessage"
                      #else
                      "failed": false
                      #end
                    }#if($foreach.hasNext),#end
                    #end
                  ]
                }
      responses:
        '200':
          description: |
            The batch was processed.  Some clicks may not have been
            processed.  The response contains a list of clicks in the same
            order submitted, indicating which succeeded and which failed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchWriteResponse"
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
x-amazon-apigateway-request-validator: all
components:
  schemas:
    DataAdImpressions:
      type: object
      properties:
        impressions:
          type: array
          items:
            $ref: "#/components/schemas/DataAdImpression"
          minItems: 1
          maxItems: 500
      required:
        - impressions
      additionalProperties: false
    DataAdImpression:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
        user:
          type: string
          format: uuid
        ad:
          type: string
          format: uuid
      required:
        - timestamp
        - user
        - ad
      additionalProperties: false
    DataAdClicks:
      type: object
      properties:
        clicks:
          type: array
          items:
            $ref: "#/components/schemas/DataAdClick"
          minItems: 1
          maxItems: 500
      required:
        - clicks
      additionalProperties: false
    DataAdClick:
      type: object
      properties:
        timestamp:
          type: string
          format: timestamp
        user:
          type: string
          format: uuid
        ad:
          type: string
          format: uuid
      required:
        - timestamp
        - user
        - ad
      additionalProperties: false
    BatchWriteResponse:
      type: object
      properties:
        records:
          type: array
          items:
            $ref: "#/components/schemas/BatchWriteRecord"
          minItems: 1
          maxItems: 500
      required:
        - records
      additionalProperties: false
    BatchWriteRecord:
      type: object
      properties:
        failed:
          type: boolean
        error_code:
          type: string
        error_message:
          type: string
      required:
        - failed
      additionalProperties: false
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
      additionalProperties: false
