BaseURL: https://${API_ID}.execute-api.${REGION}.amazonaws.com/${STAGE}
Duration: 72h
Ads:
  Count: 1000000
Users:
  Count: 1000
  ClickthroughProbability: 0.3
  ViewFrequency: 5s
  ViewVariance: 0.1
  ConsiderDuration: 1s
  ConsiderVariance: 0.1
